# Forma y Estructura de Arrays

En esta lección vamos a entender cómo **cambiar la forma y el tamaño** de los arrays de NumPy, y para eso vamos a aprender a utilizar algunos métodos especiales.

Por un lado ya hemos visto que la propiedad `.shape` sirve para conocer la **forma** de un array.

In [9]:
import numpy as np

In [10]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array.shape

(9,)

Y también disponemos de `reshape()` que sirve para **modificar su forma**.

In [4]:
array_mod = array.reshape(3, 3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Es importante tener en cuenta que el número total de elementos debe permanecer constante para cada grupo cuando aplicamos el reshape.

Un dato curioso, es que puedes usar el número negativo **-1** para alguna de las dimensiones del array, y eso hace que NumPy se base en la otra dimensión, y **calcule automáticamente** la distribución de la dimensión faltante.

In [5]:
array_mod2 = array.reshape(-1, 3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

También quiero que conozcas al método `transpose()` (que significa *transponer*), que se encarga de **voltear el array**, es decir, de cambiar las filas a columnas y las columnas a filas.

In [12]:
array_volteado = array_mod2.transpose()
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Por otro lado, para **convertir un array biidimensional en un array unidimensional**, tenemos los métodos `flatten()` y `ravel()`.

El primero de ellos, `flatten()` (que significa "achatado"), crea una copia del array original.

In [7]:
array_chato = array_mod.flatten()
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

El segundo, `ravel()`, hace algo que parece ser exactamente lo mismo…

In [8]:
array_ravel = array_mod.ravel()
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Pero la diferencia ocurre detrás de la cortina, porque `flatten()` crea una **copia** aplanada del array, lo cual ocupa memoria, mientras que `ravel()` crea una **vista** aplanada del array original, lo que es diferente en términos de eficiencia.

Estos son métodos muy simples de usar, y esta capacidad de cambiar la forma y el tamaño de los arrays es fundamental en NumPy, ya que permite manipular y preparar datos para el análisis, la visualización y el modelado. Estas operaciones son eficientes y flexibles, y facilitan el trabajo con conjuntos de datos complejos.

Forma y Estructura de los Arrays de NumPy 1
Crea un array de NumPy llamado array_original  que contenga los números del 1 al 12 y luego cambia su forma para que se convierta en un array de 3 filas y 4 columnas. Almacenalo en una variable llamada array_reshape

In [8]:
# Crear un array de NumPy con los números del 1 al 12
array_original2 = np.arange(1, 13)
 
# Cambiar la forma del array a 3 filas y 4 columnas
array_reshape = array_original2.reshape(3, 4)

NameError: name 'np' is not defined

Forma y Estructura de los Arrays de NumPy 2
Crea un array bidimensional llamado: array_original de forma (2, 3) que contenga los primeros 6 números enteros positivos. Utiliza el método correcto para cambiar sus filas por columnas. Almacenalo en una variable llamada array_modificado

In [10]:
# Crear un array de NumPy de forma (2, 3) con los primeros 6 números enteros positivos
array_original3 = np.arange(1, 7).reshape(2, 3)
 
# Utilizar el método transpose() para cambiar sus filas por columnas
array_modificado2 = array_original3.transpose()

NameError: name 'np' is not defined

Forma y Estructura de los Arrays de NumPy 3
Crea un array de 2 dimensiones array_original de forma (2, 3) que contenga los primeros 6 números enteros positivos. Identico al del ejercicio anterior. Luego, crea una copia aplanada de este array y almacénalo en una variable llamada array_aplanado

In [12]:
# Crear un array de NumPy de 2 dimensiones de forma (2, 3) con los primeros 6 números enteros positivos
array_original = np.arange(1, 7).reshape(2, 3)
 
# Crear una copia aplanada de este array usando el método flatten()
array_aplanado = array_original.flatten()

NameError: name 'np' is not defined